# Minimal Temporal install for local kind demo.
# Not for production — single-replica everything, no persistence.
server:
  replicaCount: 1

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true
  replicaCount: 1

prometheus:
  enabled: false

grafana:
  enabled: false

elasticsearch:
  enabled: false
